version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11 # Install Amazon Corretto 11
      
    commands:
      - echo "Installing Android SDK"
      - yum install -y wget unzip

      # Download and install Android SDK
      - wget -q https://dl.google.com/android/repository/sdk-tools-linux-7583922.zip -O android-sdk.zip
      - unzip -q android-sdk.zip -d android-sdk
      - export ANDROID_HOME=$PWD/android-sdk/cmdline-tools
      - export PATH=$PATH:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools
      - yes | sdkmanager --licenses
      - sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"

  build:
    commands:
      - echo "Building the Android APK"
      # Add your actual build commands here

artifacts:
  files:
    - '**/*'


