version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing Java and Android SDK"
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk
      - wget -q https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O android-sdk.zip
      - unzip -q android-sdk.zip -d android-sdk
      - export ANDROID_HOME=$PWD/android-sdk
      - export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools
      - yes | sdkmanager --licenses
      - sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"
  
  build:
    commands:
      - echo "Building the Android APK"
      # Add your actual build commands here

artifacts:
  files: 
    - '**/*'




